### ISSUE TITLE
Connection to rTorrent not established

### ISSUE THREAD

**Issue by rj452** [romancin/rutorrent-flood-docker#126]
18.03.2020 20:51:02] No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.
How to fix this? 😞

**Comment by romancin** [comment]
Paste here container logs please.

**Comment by rj452** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-getautodl: executing... 
Cloning into '/usr/share/webapps/rutorrent/plugins/autodl-irssi'...
Already up to date.
Already up to date.
[cont-init.d] 30-getautodl: exited 0.
[cont-init.d] 40-ssl: executing... 
[cont-init.d] 40-ssl: exited 0.
[cont-init.d] 50-setconf: executing... 
[cont-init.d] 50-setconf: exited 0.
[cont-init.d] 60-pyroscope: executing... 
[cont-init.d] 60-pyroscope: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
==> /config/log/rtorrent/rtorrent.log <==
1584584401 W Ignoring rtorrent.rc.
tail: cannot open '' for reading: No such file or directory

==> /config/log/rtorrent/rtorrent.log <==
1584584401 N rtorrent main: Starting thread.
1584584401 N rtorrent scgi: Starting thread.
npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}

> flood@1.0.0 start /usr/flood
> node --use_strict  server/bin/start.js

Flood server starting on http://undefined:3000.

Here's my logs.

**Comment by kvn1351** [comment]
This is because you're using 1000:1000. Unfortunately, until he fixes it, it's only working as root, i.e. 0:0.

**Comment by romancin** [comment]
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> ```
>       _         ()
>      | |  ___   _    __
>      | | / __| | |  /  \ 
>      | | \__ \ | | | () |
>      |_| |___/ |_|  \__/
> ```
> 
> ## Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donate/
> ## GID/UID
> ## User uid: 1000
> User gid: 1000
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing...
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-getautodl: executing...
> Cloning into '/usr/share/webapps/rutorrent/plugins/autodl-irssi'...
> Already up to date.
> Already up to date.
> [cont-init.d] 30-getautodl: exited 0.
> [cont-init.d] 40-ssl: executing...
> [cont-init.d] 40-ssl: exited 0.
> [cont-init.d] 50-setconf: executing...
> [cont-init.d] 50-setconf: exited 0.
> [cont-init.d] 60-pyroscope: executing...
> [cont-init.d] 60-pyroscope: exited 0.
> [cont-init.d] 99-custom-files: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> ==> /config/log/rtorrent/rtorrent.log <==
> 1584584401 W Ignoring rtorrent.rc.
> tail: cannot open '' for reading: No such file or directory
> 
> ==> /config/log/rtorrent/rtorrent.log <==
> 1584584401 N rtorrent main: Starting thread.
> 1584584401 N rtorrent scgi: Starting thread.
> npm ERR! code EACCES
> npm ERR! syscall scandir
> npm ERR! path /root/.npm/_logs
> npm ERR! errno -13
> npm ERR!
> npm ERR! Your cache folder contains root-owned files, due to a bug in
> npm ERR! previous versions of npm which has since been addressed.
> npm ERR!
> npm ERR! To permanently fix this problem, please run:
> npm ERR! sudo chown -R 1000:1000 "/root/.npm"
> glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
> errno: -13,
> code: 'EACCES',
> syscall: 'scandir',
> path: '/root/.npm/_logs'
> }
> 
> > flood@1.0.0 start /usr/flood
> > node --use_strict  server/bin/start.js
> 
> Flood server starting on http://undefined:3000.
> 
> Here's my logs.

There I can see rtorrent starts correctly. If you are trying to start a new container, i suggest you delete all the persistent data and start from scratch (maybe with the other issue you opened, there are rest of configurations of ssl).

If you have data on rtorrent instance already, we need to diagnose what's happening looking at logs directory (rtorrent.log).

**Comment by romancin** [comment]
> This is because you're using 1000:1000. Unfortunately, until he fixes it, it's only working as root, i.e. 0:0.
> 
> Delete the config folder. Set 0:0 and restart.

I have my containers running without root user without problems. This error is more aesthetic than functional, so if you are having this problem too, we need to diagnose it to see what's happening.

**Comment by kvn1351** [comment]
> > This is because you're using 1000:1000. Unfortunately, until he fixes it, it's only working as root, i.e. 0:0.
> > Delete the config folder. Set 0:0 and restart.
> 
> I have my containers running without root user without problems. This error is more aesthetic than functional, so if you are having this problem too, we need to diagnose it to see what's happening.

Ok! I'd gladly help. As soon as I get some time today I'll send the logs etc.

**Comment by romancin** [comment]
Ok @kvn1351 thank you for your help. I have built a new v4.0.1 version with the npm problem solved, you can try with it, but I suppose the problem will be still there. I have tried it on a Synology Box, no error in the log using 1024:100, and rutorrent and flood are working correctly (but they also worked with the permission error in the log).

**Comment by rj452** [comment]
I downloaded the new version and rtorrent still won't work.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-getautodl: executing... 
Cloning into '/usr/share/webapps/rutorrent/plugins/autodl-irssi'...
Already up to date.
ln: failed to create symbolic link '/root/.autodl': No such file or directory
ln: failed to create symbolic link '/root/.irssi': No such file or directory
chown: cannot access '/root/.autodl': No such file or directory
chown: cannot access '/root/.irssi': No such file or directory
Already up to date.
[cont-init.d] 30-getautodl: exited 0.
[cont-init.d] 40-ssl: executing... 
[cont-init.d] 40-ssl: exited 0.
[cont-init.d] 50-setconf: executing... 
[cont-init.d] 50-setconf: exited 0.
[cont-init.d] 60-pyroscope: executing... 
[cont-init.d] 60-pyroscope: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
==> /config/log/rtorrent/rtorrent.log <==
tail: cannot open '' for reading: No such file or directory
1585281925 W Ignoring rtorrent.rc.

> flood@1.0.0 start /usr/flood
> node --use_strict  server/bin/start.js


==> /config/log/rtorrent/rtorrent.log <==
1585281925 N rtorrent main: Starting thread.
1585281925 N rtorrent scgi: Starting thread.
Flood server starting on http://undefined:3000.

1585315844 C Caught internal_error: 'priority_queue_erase(...) could not find item in queue.'.
---DUMP---
Stack dump not enabled.

---END---

**Comment by romancin** [comment]
The error that makes rtorrent crash is 1585315844 C Caught internal_error: 'priority_queue_erase(...) could not find item in queue.'.

Have been trying to reproduce it but I can't :(

Could you please test a new instance of the container in a clean persistent directory to see if you have the same error?

Thank you.

**Comment by kokogakayui** [comment]
Hi. I have the exact same problem as @rj452 on my dedicated server (Debian 9) with UUID/GUID 1000 with a fresh install. If I change it to 0 instead of 1000 then everything works fine.

**Comment by mmgoodnow** [comment]
I'm also running into this issue. Here is a `ps -aux` output, it seems that there are two rtorrent instances, one running as root and one running as abc.
```shell
root@3898bd0aa605:/# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    200     4 pts/0    Ss+  21:17   0:00 s6-svscan -t0 /var/run/s6/services
root        35  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise s6-fdholderd
root       402  0.0  0.0    200    64 pts/0    S+   21:17   0:00 s6-supervise rtelegram
root       403  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise fpm
root       405  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise flood
root       406  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise rutorrent
root       407  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise cron
root       409  0.0  0.0    200    64 pts/0    S+   21:17   0:00 s6-supervise irssi
root       410  0.0  0.0    200     4 pts/0    S+   21:17   0:00 s6-supervise nginx
root       412  0.0  0.0   2208  1584 ?        Ss   21:17   0:00 bash ./run
abc        413  0.2  0.1 258200 35580 ?        Ssl  21:17   0:00 npm
root       414  0.0  0.0   2208  1684 ?        Ss   21:17   0:00 bash ./run
root       416  0.0  0.0   2212  1720 ?        Ss   21:17   0:00 bash ./run
root       417  0.0  0.0   5848  4468 ?        Ss   21:17   0:00 nginx: master process /usr/sbin/nginx -c /config/nginx/nginx.conf
root       434  0.0  0.0 180712 11816 ?        Ss   21:17   0:00 php-fpm: master process (/etc/php7/php-fpm.d/rutorrent.conf)
root       437  0.0  0.0   1580     4 ?        S    21:17   0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
root       440  0.0  0.0    772    32 ?        Ss   21:17   0:00 dtach -n /detach_sess/.irssi s6-setuidgid abc /usr/bin/irssi --home=/config/.irssi
abc        442  0.3  0.2  40908 37532 pts/1    Ss+  21:17   0:00 /usr/bin/irssi --home=/config/.irssi
root       446  0.0  0.0    772    36 ?        Ss   21:17   0:00 dtach -n /detach_sess/.rtorrent s6-setuidgid abc /usr/local/bin/rtorrent -n -o import=/config/rtorrent/rtorrent.rc
abc        447 94.3  3.4 638084 635840 pts/2   Rsl+ 21:17   4:24 /usr/local/bin/rtorrent -n -o import=/config/rtorrent/rtorrent.rc
abc        449  0.0  0.0   6328  2304 ?        S    21:17   0:00 nginx: worker process
abc        455  0.0  0.0 180848  9636 ?        S    21:17   0:00 php-fpm: pool rutorrent
abc        456  0.0  0.0 180848  9096 ?        S    21:17   0:00 php-fpm: pool rutorrent
abc        466  0.3  0.2 278996 52440 ?        Sl   21:17   0:01 node --use_strict server/bin/start.js
root       497  0.0  0.0   1948   560 ?        S    21:17   0:00 tail -n 1 -f /config/log/rtorrent/rtorrent.log
root       535  0.0  0.0   2428  2096 pts/3    Ss   21:17   0:00 bash
root      2702  0.0  0.0   2212  1616 ?        Ss   21:21   0:00 bash ./run
root      2705  0.0  0.0   1948   532 ?        S    21:21   0:00 sleep 1s
root      2709  0.0  0.0   1616   456 pts/3    R+   21:21   0:00 ps -aux
```

**Comment by BoKKeR** [comment]
I am facing the same issue since a few versions back. All I did was update the image and redeploy it and it stopped working. The last 100% working I remember was v4.0.1

```
chown: cannot access '/root/.autodl': No such file or directory
chown: cannot access '/root/.irssi': No such file or directory
Already up to date.
[cont-init.d] 30-getautodl: exited 0.
[cont-init.d] 40-ssl: executing...
[cont-init.d] 40-ssl: exited 0.
[cont-init.d] 50-setconf: executing...
[cont-init.d] 50-setconf: exited 0.
[cont-init.d] 60-pyroscope: executing...
usermod: no changes
[cont-init.d] 60-pyroscope: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
dtach: /detach_sess/.rtorrent: Address in use

> flood@1.0.0 start /usr/flood
> node --use_strict server/bin/start.js

Flood server starting on http://undefined:3000.

Flood server starting on http://undefined:3000.

[0mGET / [32m200 [0m4.727 ms - 460[0m
[0mGET /favicon.ico [32m200 [0m1.182 ms - -[0m
[0mGET /static/js/main.3974fc29.js [32m200 [0m8.939 ms - -[0m
[0mGET /favicon.ico [36m304 [0m0.735 ms - -[0m
[0mGET /auth/verify?1603622144653 [32m200 [0m6.093 ms - 55[0m
(node:456) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED /run/php/.rtorrent.sock

at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
(node:456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Connection refused at /run/php/.rtorrent.sock. Check these values in config.js and ensure that rTorrent is running.
[0mGET /api/client/settings [31m500 [0m6.930 ms - 102[0m
[0mGET /api/settings [32m200 [0m15.561 ms - 185[0m
[0mGET /static/media/Roboto-regular.f84cb1bf.woff2 [32m200 [0m1.418 ms - 10292[0m
[0mGET /static/media/Roboto-700.3b38c16e.woff2 [32m200 [0m2.953 ms - 10276[0m
[0mGET /static/media/Roboto-italic.4dcf65b9.woff2 [32m200 [0m0.742 ms - 11500[0m
[0mGET /static/media/Roboto-500.1afbee5a.woff2 [32m200 [0m0.656 ms - 10248[0m
[0mGET /api/activity-stream?historySnapshot=fiveMin [32m200 [0m0.999 ms - -[0m
```

**Comment by datawhores** [comment]
Some Diagnostic Help

1.sudo docker exec -it container /bin/bash

where cointainer is the name of the container, not the image
This will allow you to exec commands with the coainter


2.rtorrent -o import=/config/rtorrent/rtorrent.rc

The idea is that you will be able to see if rtorrent can even start, I found out my configration file had an error so it never ran.  However docker never showed this error.

**Comment by BoKKeR** [comment]
The problem came back on the newest version 

```
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 21-config-flood: executing...
[cont-init.d] 21-config-flood: exited 0.
[cont-init.d] 30-getautodl: executing...
Already up to date.
ln: failed to create symbolic link '/root/.autodl': No such file or directory

ln: failed to create symbolic link '/root/.irssi': No such file or directory

chown: cannot access '/root/.autodl': No such file or directory
chown: cannot access '/root/.irssi': No such file or directory
Already up to date.
[cont-init.d] 30-getautodl: exited 0.
[cont-init.d] 40-ssl: executing...
[cont-init.d] 40-ssl: exited 0.
[cont-init.d] 50-setconf: executing...
[cont-init.d] 50-setconf: exited 0.
[cont-init.d] 51-setconf-flood: executing...
[cont-init.d] 51-setconf-flood: exited 0.
[cont-init.d] 60-pyroscope: executing...
usermod: no changes
[cont-init.d] 60-pyroscope: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
dtach: /detach_sess/.rtorrent: Address in use

> flood@4.6.1 start
> node --use_strict dist/index.js "--host" "0.0.0.0" "--port" "3000" "--rtsocket" "/run/php/.rtorrent.sock"

Flood server 4.6.1 starting on http://0.0.0.0:3000

[0mGET /overview [32m200[0m 9.649 ms - 992[0m
[0mGET /static/css/main.b0f1547f3b623489294e.css [36m304[0m 1.902 ms - -[0m
[0mGET /static/js/main.c3ba6bf6.js [36m304[0m 0.650 ms - -[0m
[0mGET /favicon.ico [32m200[0m 3.318 ms - -[0m
[0mGET /static/css/185.bc338a685eec2e79b3a6.css [36m304[0m 0.364 ms - -[0m
[0mGET /static/js/185.c15fdff5.chunk.js [36m304[0m 0.969 ms - -[0m
[0mGET /static/js/90.22dd1b60.chunk.js [36m304[0m 0.859 ms - -[0m
[0mGET /api/auth/verify?1646381613857 [32m200[0m 12.956 ms - 106[0m
[0mGET /api/client/settings [31m500[0m 2.811 ms - 80[0m
[0mGET /static/js/770.6883b847.chunk.js [36m304[0m 1.170 ms - -[0m
[0mGET /static/js/834.202846e6.chunk.js [36m304[0m 0.994 ms - -[0m
[0mGET /static/js/flag6.4c238a7a.chunk.js [36m304[0m 0.525 ms - -[0m
[0mGET /c2e3c6a0636c10218ecc.woff2 [36m304[0m 0.864 ms - -[0m
Error: connect ECONNREFUSED /run/php/.rtorrent.sock

at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '/run/php/.rtorrent.sock'
}
[0mGET /7be31b83f4f0e07a580c.woff2 [36m304[0m 0.341 ms - -[0m
[0mGET /007b86f28547a5d477bb.woff2 [36m304[0m 0.313 ms - -[0m
[0mGET /0c26a238553ed08c3651.woff2 [36m304[0m 0.321 ms - -[0m
[0mGET /api/client/connection-test [31m500[0m 1.798 ms - 21[0m
[0mGET /api/settings [32m200[0m 6521.866 ms - 700[0m
[0mGET /api/activity-stream?historySnapshot=FIVE_MINUTE [32m200[0m 2.826 ms - -[0m
Error: connect ECONNREFUSED /run/php/.rtorrent.sock

at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '/run/php/.rtorrent.sock'
}
[0mGET /api/client/connection-test [31m500[0m 1.064 ms - 21[0m
[0mGET /api/client/connection-test [31m500[0m 1.163 ms - 21[0m
[0mGET /api/client/connection-test [31m500[0m 1.380 ms - 21[0m
[0mGET /api/activity-stream?historySnapshot=FIVE_MINUTE [32m200[0m 1.062 ms - -[0m
```

The container starts but I cant connect to rtorrent.sock, 

if I use 
`rtorrent -o import=/config/rtorrent/rtorrent.rc`
in the container I can start rtorrent for a while manually. Day after it was down again

**Comment by docfactory37** [comment]
i'm also having the same issue i have just setup a new instance and when its start i get the below 

No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

and im using the latest and it also happens with 0.9.8 version
